### ISSUE TITLE
Missing pokered.ini, can't create pokered-speedchoice

### ISSUE THREAD

**Issue by ViWalls** [Dabomstew/pokered-speedchoice#1]
I was trying to compile everything in Cygwin but the file 'pokered.ini' it's missing in the tools folder. The process it's stopped in that point.

I don't know where is that file, tried to find it on internet witn no results. Someone can help me? I'm missing something?

**Comment by Dabomstew** [comment]
Updated INSTALL.md to address this now; tl;dr you must do `make red` once and then plain `make` will work thereafter.
