### ISSUE TITLE
Running shoes permaoption

### ISSUE THREAD

**Issue by Dabomstew** [Dabomstew/pokered-speedchoice#7]
Holding B with the option on should raise walking to bike speed. Not sure what to do about the bike itself, maybe make it 4x speed if holding B but that would make movement very awkward.

**Comment by henderkes** [comment]
4x movement speed with the bike is nice to have and possible to adopt to. 3 page options had a funny side effect where you'd be locked into 4x speed even if you let go of B until you bonked, though. Maybe that's preventable.

Thank you a lot for your work :)

**Comment by Dabomstew** [comment]
Implemented by cffaf2e
